### ISSUE TITLE
move all dev profiles to single folder

### ISSUE THREAD

**Issue by olivia7n** [barrycumbie/dev-challenge-01#100]
move everyone's dev profiles under the dev-profile folder

**Comment by barrycumbie** [comment]
Need way more! 

user story!
story points!
approach!
background/research!

and specifics!

which files exactly! what files to move! sorry for all of these ➡️ !

**Comment by olivia7n** [comment]
User story:
As a dev for this class, I want to better organize everyone's dev profiles to a single folder so that it is easier to navigate through everyone's profiles. 

Story points:
5 points

Approach:
Relocate all dev profiles that are not inside of the dev-profile folder to that folder.

Background/Research:
Organization is extremely important in just about anything, especially when many people are coming together to work on a single project or task. It's important to have a standardized interface and look so that everyone working knows where to place their work. By moving all of the dev profiles to a single folder, it will be easier to locate these profiles.

**Comment by olivia7n** [comment]
https://docs.github.com/en/github/managing-files-in-a-repository/moving-a-file-to-a-new-location#:~:text=To%20move%20the%20file%20into%20a%20directory%20above%20the%20file's,edit%20the%20parent%20folder's%20name.

Here is a helpful link for how to move files in GitHub!

**Comment by barrycumbie** [comment]
> https://docs.github.com/en/github/managing-files-in-a-repository/moving-a-file-to-a-new-location#:~:text=To%20move%20the%20file%20into%20a%20directory%20above%20the%20file's,edit%20the%20parent%20folder's%20name.
> 
> Here is a helpful link for how to move files in GitHub!

☝🏼  let's not do this...we want to create a branch and do the changes on that branch: then do a PR.

**Comment by barrycumbie** [comment]
Check out these other recent issues: #108 and #104.

See how they use a little markdown on the user story...and my comments about which files specifically need to be moved and even the CLI commands or including the file directory tree.

You are essentially defining a work ticket for someone to be able to follow...what it was a DEV in Prague or New Dheli or San Fransico or just someone new to the REPO and not familiar with all the files and history? 
They may not know which files are supposed to go where.

is there a test associated with this?

**Comment by olivia7n** [comment]
I can't see which files need to be moved anymore

**Comment by olivia7n** [comment]
User Story

As a: collaborator
I want to: move dev profiles that are not in the dev-profile folder into that folder
So that: the repo will be easier to navigate with all profiles in a single folder

Test

1. Navigate to the REPO Source Code: https://github.com/barrycumbie/dev-challenge-01
2. Scan all files/folders, identifying files that are not in the dev-profile folder
3. Make sure the files outside of the dev-profile folder or in another folder are placed in the dev-profile folder

├── course-content
│   ├── cli-commands.html
│   ├── course-info.html
│   ├── gitbranch-iss98
│   ├── markdownSyntax.html
│   ├── pull-request-advice.html
│   └── temp.txt
├── dev-03-gitcommands
├── dev-instructions
│   └── dev-03-instructions.md
├── dev-profile
│   ├── Estacio-dev-profile.html
│   ├── alsup-dev-profile.html
│   ├── codys-dev-profile.html
│   ├── davis-dev-profile.html
│   ├── escobar-dev-profile.html
│   ├── hammond-dev-profile.html
│   ├── humphreys-dev-profile.html
│   ├── joe_dev.html
│   ├── josh-dev-challenge.html
│   ├── joshua-dev-profile.html
│   ├── luan-dev-profile.html
│   ├── owen-dev-profile.html
│   ├── reid-dev-profile.html
│   ├── sevigne-dev-profile.html
│   └── sherrill.html
├── dont-do-this.html
├── index.html
├── joshua-dev-profile.html
├── lib
│   ├── img
│   │   └── TrevorDS
│   │       └── tds_examplePR.png
│   ├── scripts
│   └── styles
└── noah-dev-profile
    └── noah-dev-profile.html

**Comment by barrycumbie** [comment]
a little lost in this one...

edit the very first comment in this issue to be up-to-date with the user story and points and test and everything. 
Take the points down to 2.

dont forget MD syntax, esp when using your dir structure

**Comment by olivia7n** [comment]
Updated the original comment to complete the dev-04 diy issue challenge. Story card now has all of the info in one place.
