### ISSUE TITLE
Add dev challenge instructions to README.md

### ISSUE THREAD

**Issue by Chelfert** [barrycumbie/dev-challenge-01#117]
### **User Story**

As a Dev,
I would like to edit the "README.md" file that is located in the root of the repository. Currently, this file has nothing useful inside of it besides the text "dev-challenge-01". I would like to change this so that other developers can have access to the dev challenge instructions locally instead of having to go to canvas for them every time. This would help speed up the process of finishing these challenges, as nobody would have to pull up a separate browser every time they wanted to work on an assignment.

### **Approach**

- Grab every set of 'dev-challenge-*' instructions and put them in their own file.
- Make sure my local repository is up to date by performing a `git pull` command.
- Creating a branch names 'iss167'
- Open 'README.md' and insert dev-challenge instructions.
- Close and save 'README.md'.
- Stage and commit file.
- Perform a `git push` command.

### **Commands**

- `git pull` to pull new data into local repository
- `git checkout -b iss167` to create a new branch on local repo.
- `git add README.md` to stage the new file.
- `git commit -m "information about change"` to commit file to repo and give information about changes.
- 'git push' to push file to master repo.

### **Test**

To test if the file has been updated, you can navigate to the root directory of the repository and open the "README.md" file with any text editor. You will see the instructions for dev-challenge 1-7. If you do not see this, then you will have to use a `git pull` command to update your local repo.

### **Points**
2

**Comment by barrycumbie** [comment]
Roger that...go for it...

1. clone our REPO (or do a ```git pull``` to update an existing clone)
2. create a branch...name it ```iss117111
3. do your work on the branch
4. send in a PR with your updates!

**Comment by barrycumbie** [comment]
For dev challenge 4 it is to submit a COMPLETE issue card (not like the bare-bones one that I permitted in DC3) 

See some others for examples, #138 #108 #152 #85.

**Comment by Chelfert** [comment]
@barrycumbie On the linked PR, am I supposed to merge the branches myself? Or is that something that I leave to you still?

**Comment by barrycumbie** [comment]
this issue is kinda bonk but look at the amended user story up top...maybe have a single page for all dev instructions
