### ISSUE TITLE
dc07/heroku account information

### ISSUE THREAD

**Issue by josephalsup** [barrycumbie/dev-challenge-01#119]
email: alsup914@gmail.com
name: Joseph Alsup

**Comment by barrycumbie** [comment]
I'll assume email = heroku acc't

> email: [alsup914@gmail.com](mailto:alsup914@gmail.com)
> name: Joseph Alsup

(my personal thing: I don't like ```mailto:``` links, like the one GH made for you automatically...reason: a cllick opens up a native app on your dev box? ugh.) 

nevertheless: you are a collab on my heroku now.

**Comment by williamoyen** [comment]
Link for dev-07
http://woyen.herokuapp.com/docs/

**Comment by barrycumbie** [comment]
technically you did deploy a branch, even though it is the ```main```

**Comment by williamoyen** [comment]
@barrycumbie I deployed it on the branch iss119 but now that I look back at heroku it does say main for some reason

**Comment by josephalsup** [comment]
Link for dev-07
http://alsup914.herokuapp.com/docs/

**Comment by barrycumbie** [comment]
> @barrycumbie I deployed it on the branch ` iss119` so I am not sure what happened. How would I check which branch it is using?

you can only tell by looking at the DEPLOY tab on HEROKU or if you know what code is different on 119 and can look there.
