### ISSUE TITLE
Remove the duplicated dev-profile folder located outside docs/

### ISSUE THREAD

**Issue by luannguyen1410** [barrycumbie/dev-challenge-01#122]
<h2>User Story</h2>
<b>As a DEV,</b><br>
<b>I want</b> to remove a duplicated folder locating at the dev-challenge-01 directory of the main branch,<br>
<b>So that</b> the repo can appear more organized as our working environment.<br>

+ On the <b>main</b> branch, a <b>duplicated dev-profile</b> folder appears at <b>dev-challenge-01/</b> after PR(#44)  is merged.
+ We're using the dev-profile folder in the <b>docs</b> directory, so the <b>duplicated dev-profile</b> outside it needs to be removed.

<h2>Approach</h2>

As collaborators, we should be able to create a new branch named <b>iss122</b>, clone the <b>main</b> branch of this REPO <a href="https://github.com/barrycumbie/dev-challenge-01">https://github.com/barrycumbie/dev-challenge-01</a> and remove duplicated files.

<h2>Test</h2>
1. Navigate to <b>dev-challenge-01/</b> of the new branch on your REPO.<br>
2. Confirm that the <b>dev-profile</b> folder located outside the <b>docs</b> folder has been removed.<br>
3. Check and make sure <b>dev-challenge-01/</b> contains only the following files: <b>index.html, LICENSE, README.md and docs</b>.<br>
4. Go into <b>docs</b> directory and check if the valid <b>dev-profile</b> folder is available.<br> 
5. Create a merge request and assign reviewers.

<h2>Difficulty</h2>
1 point

**Comment by barrycumbie** [comment]
Your # TEST is really what should go under your # APPROACH Header. 

See my comments on #131 for example of test

**Comment by luannguyen1410** [comment]
<i>APPROACH</i> and <i>TEST</i> edited.
