### ISSUE TITLE
Deploy a branch on Heroku

### ISSUE THREAD

**Issue by luannguyen1410** [barrycumbie/dev-challenge-01#127]
Account: Luan Nguyen
Email: luannm1410@gmail.com

**Comment by luannguyen1410** [comment]
I have a branch <b>iss127</b> successfully deployed to Heroku.
Link: http://lou-dev-07-deploy-app.herokuapp.com/docs/

**Comment by barrycumbie** [comment]
> I have a branch iss127 successfully deployed to Heroku.
> Link: http://lou-dev-07-deploy-app.herokuapp.com/docs/

🆒 does that deployed branch point to OUR CLASS REPO or to your fork?

**Comment by luannguyen1410** [comment]
@barrycumbie, it points to our class REPO. I'm not sure if I missed anything important in the process but I made these steps:

1. Clone <b>main</b> branch of class REPO to local REPO.
2. Create new branch <b>iss127</b> on local.
3. No editing in the source code.
4. `git push --set-upstream origin iss127` to class REPO.
5. Do a testing deployment using Heroku CLI with local REPO.
