### ISSUE TITLE
Reid Homan - Heroku Collaborator Request/Login Info 

### ISSUE THREAD

**Issue by reidhoman** [barrycumbie/dev-challenge-01#133]
Heroku email address: rhoman@una.edu

**Comment by barrycumbie** [comment]
created an APP for you & granted access. you may proceed.

**Comment by barrycumbie** [comment]
look at #168 for tips.

**Comment by olivia7n** [comment]
@reidhoman do you want to be partners for Heroku?

**Comment by reidhoman** [comment]
http://rhoman.herokuapp.com/docs/

Here is my Heroku app that points to my dev profile.

**Comment by cescobar13124** [comment]
Hey! This is my link that points from Heroku app to my profile.
https://cescobar.herokuapp.com/docs/dev-profile/escobar-dev-profile.html
