### ISSUE TITLE
Requesting to be Collaborator on Heroku 

### ISSUE THREAD

**Issue by josh-powell4** [barrycumbie/dev-challenge-01#136]
@barrycumbie 

![Screenshot (37)](https://user-images.githubusercontent.com/47085746/108896526-a961a080-75da-11eb-89d4-81ba4b95e2ec.png)

**Comment by barrycumbie** [comment]
See all of my very snarky comments on #125

**Comment by josh-powell4** [comment]
Is this it....?
jpowell4@una.edu 

@barrycumbie
