### ISSUE TITLE
Joseph Powell Heroku Acct

### ISSUE THREAD

**Issue by jpowelliv** [barrycumbie/dev-challenge-01#137]
Grant Me The Powers That Be - Collaborator @barrycumbie 
 
![Screenshot (21)](https://user-images.githubusercontent.com/47085760/108896640-cc8c5000-75da-11eb-8e68-80300e0859b1.png)

**Comment by barrycumbie** [comment]
See all of my very snarky comments on #125

**Comment by jpowelliv** [comment]
oooooooohhhhhh alrightie 

jpowelliv@una.edu @barrycumbie

**Comment by AlphaAndTheOshea** [comment]
@barrycumbie

**Comment by barrycumbie** [comment]
added to HEROKU. can proceed. 

Are you working on #125 now? You can close this issue and just submit that one. All three of you can submit the same issue card.
