### ISSUE TITLE
create a link for dev-03 instructions

### ISSUE THREAD

**Issue by thekaysev** [barrycumbie/dev-challenge-01#147]
# User Story
<b>As a</b> collaborator,
<b>I want</b> visitors of this product to have easy access to the content they're looking for
<b>So that</b> they don't have to spend time scouring the site trying to find information they're looking for.

# Approach
Collaborators of this product can access the ``` index.html ``` page and add the reference link to the top of the page.

# Test 
1. On the [live site](https://barrycumbie.github.io/dev-challenge-01/), confirm that the ```dev-03 instructions``` link is with the other instructions' links.
2. Click on the link to assure that it navigates to the correct location.
3. If the link navigates correctly, the test is complete and a PR can be submitted. 

# Difficulty
1 point

**Comment by thekaysev** [comment]
the dev-03 instructions are in the directory docs/dev-instructions, just add the link to the top of the product index.html page

**Comment by barrycumbie** [comment]
Look at mine #138 and some other ones...hmmm, like #131 and seems like @luannguyen1410 had a good test. 

As an "issue card" assignment, this card needs to be fleshed out some more with user story and points and detail and all.

**Comment by thekaysev** [comment]
Edited the issue card information to fit the requirements.

**Comment by barrycumbie** [comment]
@thekaysev really **As a** product user or website visitor or even highly-specific/situational: 

as a student, I want to find the dev-challenges
as an employer, I want to view student profiles
as an employer, I want to view sample student work
