### ISSUE TITLE
Deploy a branch on Heroku for OH

### ISSUE THREAD

**Issue by OliveHamm14** [barrycumbie/dev-challenge-01#162]
Hello @barrycumbie  here is my Heroku username :P

**Heroku Username:** OliveHamm14

**Here is a link... just in case:**  https://dashboard.heroku.com/account

Thanks!

**Comment by barrycumbie** [comment]
For the record this link: https://dashboard.heroku.com/account

is generic...it takes me to MY account. Like gmail.com wouldn't take me to your account profile. 

Also your Heroku username is your full email address...I figured it out for you. 

Next step is to deploy a branch on your APP on HEROKU & find a partner.

**Comment by OliveHamm14** [comment]
Ok, thank you! Sorry for any troubles that caused.

**Comment by Chelfert** [comment]
@OliveHamm14  Would you like to be my Heroku partner?

**Comment by OliveHamm14** [comment]
@Chelfert sure I'll be your partner!

**Comment by OliveHamm14** [comment]
@Chelfert do you have a discord account?
