### ISSUE TITLE
Deploy a branch on Heroku

### ISSUE THREAD

**Issue by Chelfert** [barrycumbie/dev-challenge-01#168]
Dr. Cumbie, here is my Heroku username: Chelfert@una.edu

I asked OliveHamm14 to be my partner for this challenge.

**Comment by OliveHamm14** [comment]
ohammond@una.edu

**Comment by Chelfert** [comment]
https://chelfert.herokuapp.com/docs/dev-profile/chelfert.html

Here is my heroku app that points to my dev profile.

**Comment by OliveHamm14** [comment]
http://ohammond.herokuapp.com/docs/

here is my link to my Heroku app that points to my dev profile: 

 http://ohammond.herokuapp.com/docs/dev-profile/hammond-dev-profile.html

**Also here is my old dev issue that was used for the start of dev 07:
#162
