### ISSUE TITLE
Group 4: Organize resources for dev-profile pages

### ISSUE THREAD

**Issue by luannguyen1410** [barrycumbie/dev-challenge-01#211]
## User Story (Story Point = XS)

**As a** DEV team member
**I want** to create a **resources** folders that used for **dev-profiles** pages inside the **lib** directory
**So that** we can have ALL the **CSS**, **JS** and *image* files of dev-profile pages to be more organized in one place. 

## Approach

As collaborators, we should be able to generate a folder named **dev-profiles-resources** inside the lib directory. The resources folder will contain the following sources: scripts for js and data files, styles for css files, images. This will be done on the content of the **iss201** branch of the REPO.

The STRUCTURE of the directories should appear similar like below:

![tree](https://user-images.githubusercontent.com/25607759/113815583-06ec1f80-9739-11eb-935f-8ff2a03478ef.PNG)

## Test

1. Check the **lib** directories and make sure it has **resources** folder for dev-profiles.
2. Check the **resources** directories and make sure it has the following folders: **scripts, styles and img**.
3. Take a picture :camera:  of the **lib** directories on the **iss211** branch and post it 👇 .

**Comment by barrycumbie** [comment]
@luannguyen1410 great start for an issue card. I've got a few suggestions:

1. Don't you mean iss211? 
> "Take a picture 📷 of the lib directories on the iss201 branch and post it 👇 ." 

(love the use of emojis) 

2. suggest for dir tree to put a "whack" at the end to designate folders:

```
 \---docs/
    +---course-content/
    +---dev-profile/
    \---lib/

4. Put the story points up near the top & let's switch to t-shirt size points. Look at my #207 

5. Why not take a screenshot of the current dir/ structure? 

Try this out: 

```bash
 tree -d dev-challenge-01/
```

**Comment by barrycumbie** [comment]
@luannguyen1410 

![t-shirt size story points ](http://agileupgrade.com/wp-content/uploads/2015/02/T-shirt-size-point-ratio.png)

**Comment by luannguyen1410** [comment]
So those are t-shirt points, I have no idea. 🤣
