### ISSUE TITLE
Widget on Website (BTC)

### ISSUE THREAD

**Issue by ewtaylor225** [barrycumbie/dev-challenge-01#220]
<h1> User story  (Story Point :S) </h1>

**As a user:** 
**I want**  to create a webpage with <em> cyrptocoin </em> widgets, 
**So that** I can view  BTC widget price btc cash widget , multiple crypto currencies

<h2> Approach </h2>

- go to https://getbootstrap.com/docs/5.0/examples/ 
- select a bootstrap you would like to use
- View page source, (right click view page source or Ctrl + U)
- copy all text you see , paste in text editor of choice
- went to https://tools.bitcoin.com/widgets/
- grabbed the short code above which widgets I wanted to add
- added html script for said widget to import widget to page.
- widget should be on site

<h3> Terminology </h3>

-BTC = Bitcoin (live ppc $57,990)
-BCH = Bitcoin Cash (live ppc $656.22)
-ppc = price per coin

<h4> Background </h4>

-beneficial for those in need of prices of coins and wanting to invest

**Comment by ewtaylor225** [comment]
Link to live test site on heroku for BTC and BCH: https://theewtaylor225.herokuapp.com/docs/course-content/widget.html

**Comment by ewtaylor225** [comment]
Process1: Got bootstrap from  https://getbootstrap.com/docs/5.0/examples/ choose one that I liked
Process 2 : Grab the boot strap from a inspect element (ctrl + shift + i) 
Process 3: Setup html doc how i wanted with the short code for each widget i obtained from  https://tools.bitcoin.com/widgets/
Process 4: got my widgets displayed , deployed site on Heroku

**Comment by barrycumbie** [comment]
# Process of launching a widget on our repo...

1. grabbing code from place one
2. where to put it 
3. where to put it. 
4. what to do.

**Comment by ewtaylor225** [comment]
![image](https://user-images.githubusercontent.com/66971337/114620180-f07e2080-9c70-11eb-83ab-f964c3a4cb80.png)

**Comment by barrycumbie** [comment]
> # Process
> 1. :Got bootstrap from  https://getbootstrap.com/docs/5.0/examples/ choose one that I liked
> 2. : Grab the bootstrap from a page source view (ctrl + U) copy all text from page source
> 3. add the copied bootstrap from clipboard to your text editor
> 4. : Setup html doc how I wanted with the short code for each widget I obtained from  https://tools.bitcoin.com/widgets/
> 5. : got my widgets displayed , deployed site on Heroku

- What is with all of these colons? ```:```
- Why not make working links with MD syntax ```[link name](linkpath)
- Process for what? make a better title. 
- when referring to keystrokes and stuff, use the MD code sytnax \` : `ctrl+u` (you have it as a capital U, which one is it?)
- what's the heroku deployment?
- (if any of this info is already on other issue comment cards, you can link to them)
  - for more about this widget, look at this [comment link](#)

**Comment by ewtaylor225** [comment]
<h1> Process for adding a BTC widget </h1>
<em> This process will explain how to quickly add a widget to a webpage</em>

**Comment by ewtaylor225** [comment]
# Model (dev challenge)

*  My widget site has a reusable data structure because its constantly updating. It is dynamic because regardless of what is happening the the widget will always go up or down based on the information sent from [Widget Site]( https://tools.bitcoin.com/widgets/).
*  link to view site <a href= "https://theewtaylor225.herokuapp.com/docs/course-content/widget.html" > Heroku Widget Deploy </a>
*  🖖🏽  🖖🏽  🖖🏽  🖖🏽 I come in peace

**Comment by ewtaylor225** [comment]
https://wayou.github.io/t-rex-runner/

**Comment by ewtaylor225** [comment]
*Full Stack* 

https://user-images.githubusercontent.com/66971337/116130834-4dc29a80-a691-11eb-8248-747c84ba173a.mp4

My full stack video and the process I took to create a simple page w a couple widgets on it . **very simple.**
