### ISSUE TITLE
Add course-content/ for Dev-03

### ISSUE THREAD

**Issue by williamoyen** [barrycumbie/dev-challenge-01#72]

**Comment by barrycumbie** [comment]
@williamoyen your branch issue-72 with the main 👍🏼 

I suspect you've made your changes ```mkdir course-content``` but haven't yet ```git push``` from your *local dev box* to the remote.

**Comment by barrycumbie** [comment]
also, @williamoyen next time name your branch like this:

```iss72```

vs 

```issue-72```

**Comment by barrycumbie** [comment]
also, also @williamoyen I'm subtly trying to nudge you *off* of CNVS Inbox and moving the discussion to the GH cards. 

You can always @barrycumbie to get my attention or just submit a link to the CNVS assignment to get my attention. 

REASON: <strike>Cumbie is being difficutl</strike> it makes sense to keep the thread of the convo all on our code repo and not lost, isolated in some other place.

**Comment by williamoyen** [comment]
When I do git push it says that everything is up to date

**Comment by williamoyen** [comment]
@barrycumbie  also  after I made the directory when I did git commit, it said there was nothing to commit

**Comment by barrycumbie** [comment]
🤔 I suspect one or some of the following:

* working on the wrong brach. need to first ```git checkout issue-72``` (use ```git branch -a``` to see where you at)
* missed one of these:
```git add <filename>```

oh wait! I got it! I'm so happy for you to learn this lesson...the more you try the more you learn 😄 

* if you ```duckduckgo``` ```git add an empty directory``` you will find that you cannot add an empty dir without some workarounds. The easiest one is to put in a temp file in there.

**Comment by williamoyen** [comment]
Ok, that is good to know, I will add a temp file and try it

**Comment by williamoyen** [comment]
@barrycumbie it worked(assuming I did it right). I submitted the pr request link to dev-03
